name: Dev build and publish Java distributions to ghcr

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot*
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      runsOn: ubuntu-latest
      gradleVersion: '6'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}